[package]
name = "bruty_server"
authors = ["skifli"]
version = "0.5.0"
edition = "2021"

[dependencies]
axum = { version = "0.7.3", features = ["ws"] }
flume = "0.11.0"
futures-util = "0.3.30"
log = "0.4"
rmp-serde = "1.1.2"
shuttle-axum = "0.49.0"
shuttle-runtime = "0.49.0"
tokio = { version = "1.40.0", features = ["full"] }

bruty_share = { path = "../bruty_share" }
