name: Build and Release

on:
  workflow_dispatch
  push:
    tags:
      - 'v*'
    paths:
      - 'bruty_client/**'

permissions:
    contents: write

jobs:
  release:
    name: Release - ${{ matrix.platform.release_for }}
    strategy:
      matrix:
        platform:
          - os_name: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            skip_tests: true
          - os_name: Linux-x86_64
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            skip_tests: true
          - os_name: macOS-x86_64
            os: macOS-latest
            target: x86_64-apple-darwin
            skip_tests: true
            
    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: ${{ matrix.platform.command }}
          target: ${{ matrix.platform.target }}
          working-directory: ./bruty_client
          args: "--release"
      - name: Publish artifacts and release
        uses: houseabsolute/actions-rust-release@v0
        with:
          binary-name: bruty
          target: ${{ matrix.platform.target }}
        if: matrix.toolchain == 'stable'